---
# /*---------------------------------------------------------------------------8
# |                                                                            |
# | This file runs common pre-provisioning tasks before the                    |
# | OS specific clustering is performed                                        |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

- name:                                "1.17 Generic Pacemaker - Ensure systemctl daemon is reloaded"
  ansible.builtin.systemd:
    daemon_reload:                     true

# Change the configuration file for the network interface to prevent the cloud
# network plugin from removing the virtual IP address (Pacemaker must control
# the VIP assignment)
# Refer to: https://www.suse.com/support/kb/doc/?id=7023633 for more information
- name:                                "1.17 Generic Pacemaker - Ensure that network interface is not managed by cloud network plugin"
  become:                              true
  ansible.builtin.lineinfile:
    path:                              /etc/sysconfig/network/ifcfg-eth0
    backup:                            true
    regexp:                            '^CLOUD_NETCONFIG_MANAGE='
    line:                              CLOUD_NETCONFIG_MANAGE='no'
  when:
    - ansible_os_family|upper == "SUSE"
  tags:
    - cloudnetmanage

- name:                                "1.17 Generic Pacemaker - Ensure the primary node public key is on the secondary node"
  ansible.builtin.authorized_key:
    user:                              root
    key:                                "{{ lookup('file','/tmp/{{ primary_instance_name }}-id_rsa.pub') }} "
  when: ansible_hostname == secondary_instance_name
  tags:
    - skip_ansible_lint

- name:                                "1.17 Generic Pacemaker - Ensure the secondary node public key is on the primary node"
  ansible.builtin.authorized_key:
    user:                              root
    key:                                "{{ lookup('file','/tmp/{{ secondary_instance_name }}-id_rsa.pub') }} "
  when: ansible_hostname == primary_instance_name
  tags:
    - skip_ansible_lint

# Clustering commands are based on the Host OS
- name:                                "1.17 Generic Pacemaker - Cluster based on OS on VM {{ ansible_hostname }}"
  include_tasks:                       "1.17.2.0-cluster-{{ ansible_os_family }}.yml"
  when:                                cluster_existence_check != 0

...
