---

# /*---------------------------------------------------------------------------8
# |                                                                            |
# |     Copy SSFS Keys                                                         |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

- name:                                "HSR - SYNC the Primary node SSFS files - fetch"
  ansible.builtin.fetch:
    src:                               "{{ item.path }}{{ item.file }}"
    dest:                              /tmp/
    flat:                              yes
  loop:
    - { file: 'SSFS_{{ db_sid | upper }}.DAT', path: '/usr/sap/{{ db_sid | upper }}/SYS/global/security/rsecssfs/data/' }
    - { file: 'SSFS_{{ db_sid | upper }}.KEY', path: '/usr/sap/{{ db_sid | upper }}/SYS/global/security/rsecssfs/key/'  }
  when:                                ansible_hostname == primary_instance_name

- name:                                "HSR - SYNC the Primary node SSFS files - copy"
  ansible.builtin.copy:
    src:                               "/tmp/{{ item.file }}"
    dest:                              "{{ item.path }}{{ item.file }}"
    owner:                             "{{ sap_hana_hsr_hana_sid | lower }}adm"
    group:                             sapsys
    mode:                              '{{ item.mode }}'
  loop:
    - { file: 'SSFS_{{ db_sid | upper }}.DAT', path: '/usr/sap/{{ db_sid | upper }}/SYS/global/security/rsecssfs/data/', mode: '0600'  }
    - { file: 'SSFS_{{ db_sid | upper }}.KEY', path: '/usr/sap/{{ db_sid | upper }}/SYS/global/security/rsecssfs/key/' , mode: '0640' }
  
  when:                                ansible_hostname == secondary_instance_name

